[[redirects]]
  from = "https://cdlpauloafonso.com/*"
  to = "https://www.cdlpauloafonso.com/:splat"
  status = 301
  force = true
[build]
  base = "frontend"
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
